# Site settings
title: Ian Maywar
description: An overview of my projects
url: "https://ijmaywar.github.io"
baseurl: "/ijmaywar"   # use "" if this is a user/organization site

# GitHub Pages theme
theme: jekyll-theme-slate

# Optional: show GitHub repo links
github:
  is_project_page: true
  repository_url: https://github.com/your-username/your-repo-name

# Markdown & syntax highlighting
markdown: kramdown
highlighter: rouge

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
