title: Ian Maywar
description: Portfolio
theme: jekyll-theme-slate

# Prevent readme from being used to build site
readme_index:
  enabled: false

# Disable GitHub links
github:
  is_project_page: false
